export const calculator = [
	{ valCalculator: '7' },
	{ valCalculator: '8' },
	{ valCalculator: '9' },
	{ valCalculator: 'DEL', deletePrevious: true },
	{ valCalculator: '4' },
	{ valCalculator: '5' },
	{ valCalculator: '6' },
	{ valCalculator: '+' },
	{ valCalculator: '1' },
	{ valCalculator: '2' },
	{ valCalculator: '3' },
	{ valCalculator: '-' },
	{ valCalculator: '.' },
	{ valCalculator: '0' },
	{ valCalculator: '/' },
	{ valCalculator: 'x' },
	{ valCalculator: 'RESET', reset: true },
	{ valCalculator: '=', equal: true },
];
